### ISSUE TITLE
Create wrapper sniff to allow for no file comment for namespaced classes

### ISSUE THREAD

**Issue by jrfnl** [Yoast/yoastcs#106]
If I remember correctly, files within the Yoast projects which have a namespace and contain an OO object declaration:
* do need a class/interface/trait docblock;
* but do **not** need a file docblock.

The current `FileComment` sniff, which WPCS includes, however, demands a file docblock for all files.

A wrapper sniff can be created which extends the existing FileComment sniff and bows out if both a namespace as well as an OO object declaration are found in a file. If either one isn't found, the normal sniff logic of the upstream sniff can be triggered.

@atimmer Could you please check this issue over and confirm whether I remembered this correctly (or comment to correct me) ?

**Comment by atimmer** [comment]
Yes, you remember correctly.

**Comment by jrfnl** [comment]
@atimmer I've been working on the wrapper sniff and just want to confirm a few details, c.q. how to handle some edge cases:

1. When a file contains a `namespace` keyword, but no actual namespace (= global namespace) => demand a file comment ?
    ```php
    namespace;
    class ABC {}
    ```
2. When a file contains one or more scoped namespaces => demand a file comment ?
    ```php
    namespace A\B\C {
        class ABC {}
    }
    namespace D\E\F {
        class ABC {}
    }
    ```
3. What about files which **_do_** contain a namespace, but no OO declaration, think files only containing namespaced functions or side effects => demand a file comment ?

4. When YoastCS would _not_ demand a file comment, but a file comment _is_ found => warn that the file comment can be removed ?

**Comment by jrfnl** [comment]
Discussed - conclusion:

1. Yes, demand comment
2. No, as namespace is known, but add a separate sniff to prohibit the use of scoped namespaces and namespace keywords without actual namespace name, but _do_ allow whitelist comments, providing they have a reason added.
3. No, this is fine.
4. Yes.

**Comment by jrfnl** [comment]
PR #111 should take care of this.
