### ISSUE TITLE
Check for correct usage of @covers tags

### ISSUE THREAD

**Issue by jrfnl** [Yoast/yoastcs#123]
The `@covers` tag in docblocks is use to denote what method/class a unit test tests and to prevent "incidental" coverage from being recorded.

"Incidental coverage" in this context, means tests calling methods other than the method under test to set up/prepare test. The resulting "lines covered" from this test set up/preparation should not be recorded.

Refs:
* https://phpunit.readthedocs.io/en/8.0/code-coverage-analysis.html 
* https://phpunit.readthedocs.io/en/8.0/annotations.html#covers

These tags are only effective when used correctly and various versions of PHPUnit may have varying degrees of tolerance for incorrectly used `@covers` tags.

If a `@covers` tag is ignored because it is incorrect, code coverage for incidental coverage could be recorded, skewing the code coverage figures.

I would like to propose a new sniff to check the following:
* That all unit tests have a `@covers` tag either at the class or the method level.
    A `warning` should be thrown if the `@covers` tag is missing.
* That the content of the `@covers` tag is in a valid format as specified by the PHPUnit documentation.
    An `error` should be thrown when an invalid format is encountered and whenever possible this format should be auto-fixed.

Implementation notes:
* What classes/methods should be considered test classes/methods can be derived from the PHPUnit config file, if available.
    If not available, the sniff should either bow out or use sensible defaults which can be adjusted via the PHPCS config file.
* If a test method/class does not have a docblock, bow out. That is covered by another sniff.

**Comment by IreneStr** [comment]
Sounds like a good idea to me. What do you think @moorscode?

**Comment by jrfnl** [comment]
@moorscode @omarreiss Had a chance to look at this proposal yet ?

This sniff should be easy enough to write and implement and the time to write this sniff will be won back when offset against the time which would be needed to manually fix the tags.

Along the same lines, but a separate issue, I've also seen the `@expectedException` tag being used incorrectly which invalidates the test. A sniff for that could also be written.
See: https://github.com/Yoast/wordpress-seo/pull/12481

**Comment by herregroen** [comment]
Just discussed this proposal with @jrfnl and I agree this should be added 👍
