### ISSUE TITLE
Sniff to enforce usage WPSEO_Utils:format_json_encode

### ISSUE THREAD

**Issue by omarreiss** [Yoast/yoastcs#124]
In https://github.com/Yoast/wordpress-seo/pull/12537, we're adding a util `WPSEO_Utils:format_json_encode()` which uses `wp_json_encode()` under the hood, adds a `JSON_UNESCAPED_SLASHES` flag if the PHP version > 5.4 and pretty prints if `WP_DEBUG` is enabled.

I want to enforce the util to be used everywhere instead of `wp_json_encode` and `json_encode`. We can also autofix.

**Comment by jrfnl** [comment]
Specs are clear, so PR #125 should fix this.
