### ISSUE TITLE
Add a sniff to disallow `@return` type `mixed` in docs

### ISSUE THREAD

**Issue by IreneStr** [Yoast/yoastcs#196]
Add a sniff to disallow `@return` type `mixed` in the documentation.

**Comment by jrfnl** [comment]
This can be addressed using the `SlevomatCodingStandard.TypeHints.DisallowMixedTypeHint` in YoastCS 3.0.0. Also see #208.

**Comment by jdevalk** [comment]
@jrfnl did we do this already? is it possible to do this already?
