### ISSUE TITLE
Add sniff to detect `get_option`/`update_option` usage with prefix in name (`wpseo_`)

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastcs#222]
We have our own `WPSEO_Options` framework. This should be used for all interactions with options.
So any calls to `get_option` or `update_option` with a specific prefix should result in an error in the sniffs.

Whenever we want to allow these specifically, sniff-excludes should be used to mark them.

**Comment by jrfnl** [comment]
Closing as duplicate of #69
