### ISSUE TITLE
Output escaping sniff should take into account presenters

### ISSUE THREAD

**Issue by omarreiss** [Yoast/yoastcs#223]
When we want to output HTML, we usually use presenters like this.

`echo new Meta_Fields_Presenter( $this->get_metabox_post(), 'general' );`

This triggers the output escaping sniff everywhere the presenter is used. Can we make sure we don't trigger the sniff on presenters like this? Instead we could analyze the `present` method on every presenter. That is were data should be escaped before it is included in the html output.

**Comment by jrfnl** [comment]
Well, from a late escaping point of view, using that code snippet is an anti-pattern and not something we will ever be able to account for.

The pattern to use in that case would be:

```
new Meta_Fields_Presenter( $this->get_metabox_post(), 'general' );
```

And move the `echo` to the code in the presenter where the output escaping can be checked.

**Comment by omarreiss** [comment]
Strictly from a code perspective, you're right. But in the domain the presenter already functions as the "edge". It's the class that invokes / contains the view and the view is the place where things should be escaped. 
`echo new Meta_Fields_Presenter( $this->get_metabox_post(), 'general' );` is equivalent to 
`require './views/some_view.php`, where the escaping would also happen inside the view, and not in the place where the view is required. 

The view could work with `echo` statements, or with interpolated HTML, or with some kind of handlebars style templates. It doesn't really matter. We simply build up the HTML as a properly escaped string of html and echo it via the `__toString` which is magically set on the abstract parent. That pattern brings us great ease of use so we'd like to support it.

**Comment by jrfnl** [comment]
@omarreiss I totally understand that the pattern used works well, except this is not a pattern which the WPCS sniff will be adjusted for, for two reasons:
1. The sniff is based on late escaping and what's being echo-ed out is not being late escaped (but "early" escaped).
2. There are no checks in place to verify that the Presenters actually do the escaping correctly.

I'll have a think about creating a wrapper around that sniff for YoastCS, which bows out when it sees the `new Presenter()`pattern, but that would still only solve [1].
There would be no guarantee that HTML returned by the presenters is escaped properly (nor is there now).

**Comment by omarreiss** [comment]
Ah sorry, didn't realize that's a WPCS sniff 😅 . Of course I wouldn't want to change that 😄 ! Thanks for thinking along for how we can accomodate Yoast CS.

> There would be no guarantee that HTML returned by the presenters is escaped properly (nor is there now).

I agree it would be quite impossible to sniff that well. Think it would be fine if the sniff would always trigger on `present` just to remind the developer about output escaping. They can put the ignore in the file after they've been confronted with the concern.

**Comment by jrfnl** [comment]
> They can put the ignore in the file after they've been confronted with the concern.

Will also be a good reminder to verify the presenter if they were working on that when making the change which triggers the error.

Either way, with that in mind, can this issue be closed ?
