### ISSUE TITLE
Trait double doesn't need a trait suffix

### ISSUE THREAD

**Issue by andizer** [Yoast/yoastcs#235]
When a double has been made for a trait the CS expects to have it suffixed with `-trait`. This can lead to weird file naming with a lot of traits in it. 

When it is a double or is in the doubles directory we should just append `-double` to it.

![wordpress-seo_–_composer_json](https://user-images.githubusercontent.com/325040/99683664-e15bc380-2a80-11eb-98da-e1248dcd3e1d.png)

**Comment by jrfnl** [comment]
Solution: change the Double/Mock to a class which uses the trait. Problem solved.
