### ISSUE TITLE
Add a sniff for console.log

### ISSUE THREAD

**Issue by increddibelly** [Yoast/yoastcs#236]
we shouldn't have console.log in production code; adding a sniff could easily help us prevent this.

**Comment by increddibelly** [comment]
we already have a sniff for this <3

**Comment by jrfnl** [comment]
@increddibelly I suppose you mean a ESLint check ? AFAIK `console.log` is not being sniffed for and I'd recommend against writing a sniff for it as JS support will be removed in PHPCS 4. For PHP, there is the `WordPress.PHP.DevelopmentFunctions` sniff which checks for things like `error_log()` and `var_dump()`.
