### ISSUE TITLE
@subpackage tag

### ISSUE THREAD

**Issue by Rarst** [Yoast/yoastcs#3]
The current iteration of ruleset mandates `@subpackage` tag in file headers.

However, it is [deprecated in PSR–5 draft](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#819-subpackage-deprecated).

I think it would make sense to omit it as hard requirement. Thoughts?

cc @jrfnl

**Comment by jrfnl** [comment]
+1
