### ISSUE TITLE
YoastCS native filename sniff

### ISSUE THREAD

**Issue by jrfnl** [Yoast/yoastcs#48]
As discussed with @moorscode and by @moorscode discussed with @omarreiss and @atimmer, I'm working on a YoastCS native filename sniff.

There are a couple of things I need to get a decision on before the sniff can be finalized, so Jip, Omar, Anton, please discuss and let me know the outcome.

Currently implemented rules:
* (WP) Filenames should be lowercase and words should be separated by dashes (not underscores).
* All class files should only contain one class (enforced by another sniff in WPCS) and the file name should reflect the class name without the plugin specific prefix.
* All interface and trait files should only contain one interface/trait (enforced by another sniff in WPCS) and the file name should reflect the interface/trait name without the plugin specific prefix and with an `-interface` or `-trait` suffix.
* Files which don't contain an object structure, but do contain one or more function declarations should have a `-functions` suffix.

Currently implemented exception:
* It will be possible to pass one or more file names to the sniff to exclude.
    This has been done to allow for "main" plugin files which may contain functions, but don't have the `-functions` suffix. Renaming the file would lead to deactivation of the plugin on upgrade which is probably not a good idea.

Open questions:
* For the file names to be excluded, should this just be a file name or should this be a path from the root of a plugin and strictly checked against the path ? If it's just a file name, you run the risk that another file in another directory would use the same name and be excluded from this sniff as well.
* Should this sniff be set up to be able to also check the filenames of CSS and JS files ?
* Should the "functions" rule be applied when a file **_only_** contains functions (no side-effects) or also when the file contains functions as well as miscellaneous code ?
    Think: WPSEO Free `admin/pages/metas.php`.
* What about interfaces/classes/traits which have the word `Interface/Class/Trait` in the object name ?
    Think: WPSEO Free `WPSEO_Sitemap_Cache_Data_Interface`
* Should there be a rule about abstract classes ? Should they have an `abstract` prefix/suffix or should this just be the same as the class name ?
* Keeping in mind the intention to move to a PSR based namespace folder structure - should a potential overlap with the directory name a class lives in be removed ?
    Think: WPSEO Free class `WPSEO_Metabox_Tab_Section` which currently lives in file `admin/metabox/class-metabox-tab-section.php`:
    Should this become `metabox-tab-section.php` as per the above rules or should this become `tab-section.php` ?
   And if the latter: what about classes which are named the same as their directory path ? Think `WPSEO_Tracking` in `admin/tracking`.
* Test class files, now all start with `test-class`. For PHPUnit, having the `test-` prefix (or a `-test` suffix) is needed.
    - Should the `class-` bit stay or go ?
    - Should the filename match the class name more closely ? The order is reversed at the moment.
        Class names for test classes generally follow the following pattern: `Prefix_Classname_Test` with the `Prefix` and the `Test` suffix being fairly consistently applied and `Classname` reflecting the name of the class under test.
        File names for test classes generally follow the following pattern at this time: `test-class-classname.php`.
        Using the "normal" rules for classes, the file name should/would become: `classname-test.php`.
        Example:
              - Current file name: `test-class-redirect-table.php`
              - Class name: `WPSEO_Redirect_Table_Test`
              - Expected file name using "normal" rules: `redirect-table-test.php`
    - In other word; how would you like me to handle test files ?
    - And what to do about test classes which are inconsistently named ? Think: `Test_Yoast_Notification`.
* And what about test Mock/Double classes ? Should they follow the file name rules for "normal" classes ?

Reading back over my own questions, I'm thinking that maybe there should be a YoastCS `ClassName` sniff as well to prevent some of the classname inconsistencies I've listed about.

Maybe something along the lines of:
* Don't use `interface`, `class`, `trait` or `abstract` in the object name.
* OO Structures in the plugin should follow the following pattern: `Prefix_[Optional:Subdir_]Classname` where a couple of "basepaths" can be taken into account, such as `admin` or `premium` which don't need to be in the name.
* Test OO Structures do not need a prefix (as they won't be shipped with the plugin) and should follow the following pattern: `[Optional:Subdir_]Classname_Test`.

What do you think ?

It won't be much work to write this sniff, providing the specs are clear.

### Attachments

Current file rename proposal based on the above:
[wpseo-file-rename-proposal.xlsx](https://github.com/Yoast/yoastcs/files/1400732/wpseo-file-rename-proposal.xlsx)

Notes:
* Take note of the two tabs - one for the WPSEO Free plugin, one for the Premium plugin.
* For this list, I've taken two class prefixes into account: `WPSEO` and `Yoast`.
* For the `Free` plugin, the list will not be entirely correct yet as there are still 26 files (2 in the plugin, 24 in the tests) in Free which contain two or more classes and need to be split.
* For the `Premium` plugin, the above mentioned split has already been done.

Raw data in CSV format in case you want to have a play with it (`.csv` files can't be uploaded here, so renamed to `txt`):
[wpseo-free-file-rename.txt](https://github.com/Yoast/yoastcs/files/1400735/wpseo-free-file-rename.txt)
[premium-file-rename.txt](https://github.com/Yoast/yoastcs/files/1400734/premium-file-rename.txt)

**Comment by moorscode** [comment]
Answers to your questions:

### Excluding files
Please exclude using the full path, we want to discourage introducing any new exclusions being introduced.

### Also implement for CSS/JS
No. Not at this point.

### `-functions.php` exclusions
We want to have file-specific full-path excludes. Also discouraging any new entries from being created.

### Interface name
These can be ignored in file name comparison, expected result would be:
`interface WPSEO_Sitemap_Cache_Data_Interface` > `sitemap-cache-data-interface.php`

### Abstract classes
Just use the class name as guidance, ignore the `abstract` part.

### PSR based namespace folder structure
As we will not move everything to a PSR structure, but gradually convert classes while keeping the old API functional, this is not something we want to consider at the moment.
Especially to make sure nobody thinks we are using PSR as we are not.

### Test files
Moving the `test` identifier to the end of the file is desired.
For example: `WPSEO_Redirect_Table_Test` > `redirect-table-test.php`

For Mock/Double files, the regular naming conventions can be applied, as these classes need to have `mock` or `double` as suffix anyway to avoid class name conflicts.

---

# Sniffs

#### Don't use interface, class, trait or abstract in the object name.
We are not going to remove interface suffixed interfaces at this point, this will be implemented and taken care of during the PSR era.

#### Test OO Structures do not need a prefix (as they won't be shipped with the plugin) and should follow the following pattern: [Optional:Subdir_]Classname_Test.
Agreed.
	
#### OO Structures in the plugin should follow the following pattern: Prefix_[Optional:Subdir_]Classname where a couple of "basepaths" can be taken into account, such as admin or premium which don't need to be in the name.

This is also something we want to do when going to PSR, not before.
Premium or Admin are identifiers which are currently critical to identify specific classes which could also use a name in another scope, so keeping these in the file name would be preferable at this point.

---

I hope I described it clearly, hope this resolves any questions and blockages!

**Comment by jrfnl** [comment]
@moorscode Thanks for getting back to me. Still some more questions to confirm my understanding of your reply.

> -functions.php exclusions
> We want to have file-specific full-path excludes. Also discouraging any new entries from being created.

Do I understand correctly, that you want to use an exclude list for this, not a file content based examination (file containing only functions vs mixed content) ? 

And do I understand correctly that you want to be able to set a second list of files to exclude specifically for the suffixes ?
Or do you want the original `exclude` list only to come into effect after the "normal" lowercase-dashes rule, but before the checks for `-functions.php` or other suffix rules ?

> Abstract classes
> Just use the class name as guidance, ignore the abstract part.

Ignore as in _treat it like any other word in a class name_ or ignore as in _remove_ ?
So: should `class WPSEO_Abstract_Capability_Manager {}` be translated to filename
* `abstract-capability-manager.php` or 
* `capability-manager.php`

> Test files
> Moving the test identifier to the end of the file is desired.
> For Mock/Double files, the regular naming conventions can be applied, as these classes need to have mock or double as suffix anyway to avoid class name conflicts.

So this would basically mean that "normal" file name rules can be applied to all files in the test directory. Correct ?

> Test OO Structures do not need a prefix (as they won't be shipped with the plugin) and should follow the following pattern: [Optional:Subdir_]Classname_Test.
> 
> Agreed.

Based on this and the other remarks under "Sniffs", I conclude that a `YoastCS.NamingConventions.ValidClassName` sniff is desired.
At this moment, this sniff would **only** address the test classes (i.e. classes with a `Test` suffix which extend a known unit test case class).
The sniff would currently only verify that those classes do **not** use a plugin based prefix.
Prefixes can be provided via the ruleset of a plugin.

Do you also want the sniff to check that if the test file is in a subdirectory, that the subdirectory name is reflected in the classname ?

At a later point in time (PSR era), this sniff can then be extended to also examine non-test-classes.

> Premium or Admin are identifiers which are currently critical to identify specific classes which could also use a name in another scope, so keeping these in the file name would be preferable at this point.

The issue I was addressing was that those are current **NOT** in the class name, nor in the file name (they are in the file path), leading to the risk you describe ....


Once I've received your reply to the above questions, I will provide you with new lists of the filename (and test classname) renames which would result from this for you to examine.

**Comment by moorscode** [comment]
We want all files to be lowercased and dashed.
We want to have a list of files to be excluded from the `-functions.php` suffix for files without a class inside.

Which sounds like the later to me:
> Or do you want the original exclude list only to come into effect after the "normal" lowercase-dashes rule, but before the checks for -functions.php or other suffix rules?

**Comment by moorscode** [comment]
> Ignore as in treat it like any other word in a class name or ignore as in remove ?
> So: should class WPSEO_Abstract_Capability_Manager {} be translated to filename
`abstract class WPSEO_Abstract_Capability_Manager {}`

Is expected to be in the file: `abstract-capability-manager.php`

**Comment by moorscode** [comment]
> Based on this and the other remarks under "Sniffs", I conclude that a YoastCS.NamingConventions.ValidClassName sniff is desired.
> At this moment, this sniff would only address the test classes (i.e. classes with a Test suffix which extend a known unit test case class).
> The sniff would currently only verify that those classes do not use a plugin based prefix.
> Prefixes can be provided via the ruleset of a plugin.

>Do you also want the sniff to check that if the test file is in a subdirectory, that the subdirectory name is reflected in the classname ?

I think I was a bit quick on this particular part.

We expect the following test class:
`WPSEO_OnPage_Option_Test`

To be in the file:
`onpage-option-test.php`

Which would just follow the "regular" rules on filenames for the rest of the project, right?

I don't think we need to add complexity on the subfolder part.

**Comment by moorscode** [comment]
> The issue I was addressing was that those are current NOT in the class name, nor in the file name (they are in the file path), leading to the risk you describe ....

If they are not there at this moment, they should not be added at this point.

I'm creating an issue on the Roadmap repository to create conventions for the PSR implementations.

**Comment by moorscode** [comment]
Empty for now, but this is the issue mentioned: https://github.com/Yoast/roadmap/issues/29

**Comment by jrfnl** [comment]
> We want to have a list of files to be excluded from the -functions.php suffix for files without a class inside.

Just to be clear: this `exclude` list will be applied to class/interface/functions etc as otherwise if a plugin "main/bootstrap" file is for instance class-based, you'd still run the risk of it being renamed and the original intend of the `exclude` property was to prevent the plugin "main/bootstrap" file from getting renamed as that would deactivate the plugin on upgrade.

So, yes, will implement like this:

> Or do you want the original exclude list only to come into effect after the "normal" lowercase-dashes rule, but before the checks for -functions.php or other suffix rules?

**Comment by jrfnl** [comment]
>  think I was a bit quick on this particular part.
> 
> We expect the following test class:
> `WPSEO_OnPage_Option_Test`
> 
> To be in the file:
> `onpage-option-test.php`
> 
> Which would just follow the "regular" rules on filenames for the rest of the project, right?

So, no need for a class-name sniff at this moment and no removing of existing plugin specific prefixes from test class names for now ?

**Comment by jrfnl** [comment]
> Empty for now, but this is the issue mentioned

I don't have access to that repo, but I believe you :wink: 
Unless you want my feedback on the issue ? In that case, I'd need access.

**Comment by jrfnl** [comment]
Updated file rename proposal based on the above exchange:
[20171031 wpseo-file-rename-proposal.xlsx](https://github.com/Yoast/yoastcs/files/1430996/20171031.wpseo-file-rename-proposal.xlsx)

**Please review the proposal carefully and let me know if any more changes are desired.**

Notes:
* Take note of the two tabs - one for the WPSEO Free plugin, one for the Premium plugin.
* For this list, I've taken two class prefixes into account: `WPSEO` and `Yoast`.
* For this list, I've only excluded the plugin bootstrap files of each plugin, nothing else.

Raw data in CSV format in case you want to have a play with it (`.csv` files can't be uploaded here, so renamed to `txt`):
[20171031-wpseo-free-file-rename.txt](https://github.com/Yoast/yoastcs/files/1430993/20171031-wpseo-free-file-rename.txt)
[20171031-premium-file-rename.txt](https://github.com/Yoast/yoastcs/files/1430992/20171031-premium-file-rename.txt)


### Summary

Plugin | Total files | Files which would be renamed
--- | --- | ---
WPSEO Free | 456 | 394
WPSEO Premium | 161 | 149
