### ISSUE TITLE
Re-evaluate and optimize travis build

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoastcs#55]
Following up on the comment placed on this PR: https://github.com/Yoast/yoastcs/pull/52

We should re-evaluate if we can optimize the build script by only loading and configuring the elements we really need for a run.

**Comment by jrfnl** [comment]
Side-note: something else which you may or may not want to address in this ticket:

The travis build for YoastCS itself uses the `master` branches of WPCS as well as PHPCompatibility to test the code style of the YoastCS code.
Those `master` branches are not necessarily the same as the versions defined in the `composer.json` file.
This could be synchronized by removing the `git clone`s from the Travis script in favour of doing a `composer install`.
This will make the builds a little slower.

On the up-side: leaving things as they are, will mean that YoastCS has an "early warning" system in place for when the rulesets need updating.
In that case, it may be useful to configure a regular (monthly?) build in TravisCI to auto-run the build check independent of PRs.

**Comment by moorscode** [comment]
I would suggest to keep that in place and just make sure that we only configure and load elements in the script that are really needed for specific builds instead of altering the builds that are being run.

**Comment by jrfnl** [comment]
@moorscode I'm not sure I understand what you mean ... ?

**Comment by moorscode** [comment]
I looked into it and it turned out I missed a bit of thinking.
It seems that the travis build is optimized already.
