### ISSUE TITLE
Audit and integrate upstream Docs ruleset

### ISSUE THREAD

**Issue by Rarst** [Yoast/yoastcs#8]
The `WordPress-Docs` ruleset had been added to WPCS upstream.

Rules should be adjusted in lines with it (a lot of our custom docs rules are likely superseded by it).

See [WordPress-Docs/ruleset.xml](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Docs/ruleset.xml).

**Comment by jrfnl** [comment]
> a lot of our custom docs rules are likely superseded by it

More then likely as they are based on the same source for the initial set-up ;-)
