### ISSUE TITLE
Suggestion: sniff to check that deprecated methods are ignored for code coverage

### ISSUE THREAD

**Issue by jrfnl** [Yoast/yoastcs#95]
Related to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/993 which proposes a sniff to check various other aspects of deprecated functions/methods.

In addition to the WPCS sniff, I would like to suggest a sniff to check that any function/method which has a `@deprecated` tag in the Yoast plugins, also has a `@codeCoverageIgnore` tag.

Files which are in a `deprecated` folder could be ignored for this sniff (presuming that the PHPUnit code coverage configuration ignores those anyway).

Opinions ?

**Comment by IreneStr** [comment]
Sounds like a plan. I think there is no reason for calculating coverage for deprecated functions.

**Comment by moorscode** [comment]
That sounds great, I'm all for it!

**Comment by jrfnl** [comment]
In that case, I may as well write it now instead of doing the manual check I was working on ;-)

**Comment by jrfnl** [comment]
See PR #96
